# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 4d8c1c07c3a6422a4e468636efd347686c40ddff7fcbeb29b0bd0398ecf3020c85d2d0ff73df3d8bf9cc5c1e17743f4b80cd7b226819cd568e24b4b0a07252bc

test:
  secret_key_base: 70975898a4c4f62339cce425b95b726b5fab4245e6c11471ef2ce2fb013549e5ca449f0b439978d5d6139473a60d120f9a1cfe85638692c37b1c2b423b666697

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
